PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Check whether the dataset has been changed since the last run
SELECT (?dateModified AS ?identifier) ?isChanged
WHERE {
  <https://data.colonialcollections.nl/Bronbeek/Stamboeken> schema:dateModified ?rawDateModified .
  BIND(xsd:dateTime(?rawDateModified) AS ?dateModified)
  BIND("?_currentIdentifier"^^xsd:dateTime AS ?currentDateModified)
  BIND(?dateModified > ?currentDateModified AS ?isChanged)
}
