PREFIX schema: <https://schema.org/>

# Use a 'scrollable cursor' - https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed
SELECT *
WHERE {
  {
    SELECT ?this
    WHERE {
      ?this a schema:Person ;
        schema:isPartOf <https://colonial-heritage.triply.cc/Bronbeek/Stamboeken> .
    }
  }
}
LIMIT ?_limit
OFFSET ?_offset
